name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install frontend dependencies
        run: |
          cd ProofTrack
          npm ci
      - name: Build frontend
        run: |
          cd ProofTrack
          npm run build --if-present
      - name: Test frontend
        run: |
          cd ProofTrack
          npm test

  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install backend dependencies
        run: |
          cd back-end
          npm install jest --save-dev
          npm ci
      - name: Test backend
        run: |
          cd back-end
          npm test
