name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_backend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      - name: 'Create env file'
        run: |
          cd back-end
          touch .env
          echo AZURE_SQL_SERVER=prooftrack.database.windows.net >> .env
          echo AZURE_SQL_DATABASE=ProofTrack >> .env
          echo AZURE_SQL_USERNAME=prooftrackAdmin >> .env
          echo AZURE_SQL_PASSWORD=CSE403prooftrack >> .env
          echo AZURE_SQL_PORT=1433 >> .env
          echo AZURE_STORAGE_ACCOUNT_NAME=prooftrack >> .env
          echo AZURE_STORAGE_ACCOUNT_KEY=tI1BbRl2IZfdvTxNurRUic/0y4WKtYjrWRd5swDZ2v/4FkIvcClJC8M6/sYxr1kAQ3ftlz/Z1P+q+AStJfPpFA== >> .env
          echo AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=prooftrack;AccountKey=tI1BbRl2IZfdvTxNurRUic/0y4WKtYjrWRd5swDZ2v/4FkIvcClJC8M6/sYxr1kAQ3ftlz/Z1P+q+AStJfPpFA==;EndpointSuffix=core.windows.net >> .env
          echo AZURE_STORAGE_CONTAINER_NAME=demo >> .env
      - name: Install backend dependencies
        run: |
          cd back-end
          npm install jest --save-dev
          npm i supertest
          npm i pm2
          npm ci
      - name: Test backend
        run: |
          cd back-end
          //pm2 delete index
          npm test
      - name: Start backend server
        run: |
          cd back-end
          pm2 start index.js
          pwd
          pm2 save
