name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_backend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install backend dependencies
        run: |
          cd back-end
          npm install jest --save-dev
          npm i supertest
          npm i pm2
          npm ci
      - name: Test backend
        run: |
          cd back-end
          pm2 delete index
          npm test
      - name: Start backend server
        run: |
          cd back-end
          pm2 start index.js
          pwd
          pm2 save
